# Numpy tutorial

### Motivation. Why to use Numpy at all. 

In [9]:
import numpy as np

In [13]:
%%time 

# %%time prints the time required to execute the cell


num = 10**6 # size of the list or number of elments in the list
list1 = [1]*num
list2 = [2]*num

list1np = np.array(list1)
list2np = np.array(list2)

CPU times: user 124 ms, sys: 31.9 ms, total: 156 ms
Wall time: 154 ms


In [17]:
%%time

# Time required to multiply the input using for loops
for i in range(num):
    list1[i]*list2[i]

CPU times: user 142 ms, sys: 2.8 ms, total: 145 ms
Wall time: 142 ms


In [18]:
%%time

# Time required to multiply the input using for Numpy
new = list1np*list2np

CPU times: user 5.47 ms, sys: 2.83 ms, total: 8.3 ms
Wall time: 5.89 ms


### The Basics

### How to read the dimension of the array

In [19]:
b = np.array([[[1,2,3],[4,5,6]]], dtype='float64')
b

array([[[1., 2., 3.],
        [4., 5., 6.]]])

In [20]:
# Get Dimension
b.ndim

3

In [21]:
# Get Shape
b.shape

(1, 2, 3)

In [22]:
# Get Type
b.dtype

dtype('float64')

In [23]:
# Get Size or number of bytes (1 byte has 8 bits)
b.itemsize

8

In [24]:
# Get number of elements
b.size

6

In [25]:
# Get total size or b.itemsize*b.size
print(b.nbytes)
assert b.itemsize*b.size == b.nbytes

48


### Accessing/Changing specific elements, rows, columns, etc

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.shape, a

((2, 7),
 array([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]))

In [29]:
# Get a specific element [r, c]
a[0,4]

5

In [30]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [32]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:1]

array([2, 3, 4, 5, 6])

In [33]:
# Getting shobhit level fancy
np.append(np.append(a[:,:2], a[:,3:5],axis=1), a[:,-1:],axis=1)

array([[ 1,  2,  4,  5,  7],
       [ 8,  9, 11, 12, 14]])

In [35]:
# To change the specfic element of the array
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [37]:
# To change the specfic elementS of the array i.e., changing more than one element at once
a[:,2] = [1,2]
a.shape, a

((2, 7),
 array([[ 1,  2,  1,  4,  5,  6,  7],
        [ 8,  9,  2, 11, 12, 20, 14]]))

# 3-d example

In [38]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b.shape, b

((2, 2, 2),
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]))

In [39]:
# Get specific element (work outside in)
b[1:2,1:2,0:2]

array([[[7, 8]]])

### Initializing Different Types of Arrays

In [42]:
# All 0s matrix
a = np.random.random((1,4,1,1,1))
a

array([[[[[0.66516746]]],


        [[[0.16494953]]],


        [[[0.49179826]]],


        [[[0.68087688]]]]])

In [46]:
# Getting shobhit level fancy AGAIN
np.append(a[:2,:], a[-1:,:], axis=0)

array([[[[[0.66516746]]],


        [[[0.16494953]]],


        [[[0.49179826]]],


        [[[0.68087688]]]],



       [[[[0.66516746]]],


        [[[0.16494953]]],


        [[[0.49179826]]],


        [[[0.68087688]]]]])

In [47]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [48]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [49]:
# Any other number (full_like)
np.full_like(a, 4)

array([[[[[4.]]],


        [[[4.]]],


        [[[4.]]],


        [[[4.]]]]])

In [50]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.31689348, 0.88418619],
       [0.78509323, 0.00621657],
       [0.27334649, 0.89705669],
       [0.27442305, 0.25737202]])

In [51]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2, -3,  5],
       [-2,  4, -3],
       [ 6,  2,  0]])

In [52]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [54]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [55]:
a = np.array([1,2,3])
print(a)
b = a
b[0] = 100
print(b)
# what is the a array ? 
# print(a)

[1 2 3]
[100   2   3]


In [56]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

# a,b

### Mathematics

In [57]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [58]:
a + 2

array([3, 4, 5, 6])

In [59]:
a - 2

array([-1,  0,  1,  2])

In [60]:
a * 2

array([2, 4, 6, 8])

In [61]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [62]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [63]:
a ** 2

array([ 1,  4,  9, 16])

In [64]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [65]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [66]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [67]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [69]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [70]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.min(stats)

1

In [72]:
np.max(stats, axis=1)

array([3, 6])

In [73]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [74]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [75]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2]) # # no of columns between these 2 arrays should be same

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
# Horizontal  stack 
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2)) # no of rows between these 2 arrays should be same

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])