In [1]:
# this is program to calculate the orthogonal vectors from given basis vector
import numpy as np
V = np.matrix([[1,1,1],[-1,0,1],[1,1,2]])
V

matrix([[ 1,  1,  1],
        [-1,  0,  1],
        [ 1,  1,  2]])

In [2]:
a1 = V[:,0]
a1

matrix([[ 1],
        [-1],
        [ 1]])

In [3]:
u1 = a1
u1

matrix([[ 1],
        [-1],
        [ 1]])

In [6]:
a2 = V[:,1]
a2

matrix([[1],
        [0],
        [1]])

In [5]:
V2=a2
V2

matrix([[1],
        [0],
        [1]])

In [8]:
v2u1dot = np.linalg.norm(np.transpose(u1)@V2)
v2u1dot

2.0

In [9]:
u1mag = np.linalg.norm(u1)
u1mag

1.7320508075688772

In [10]:
u2 = V2 - (v2u1dot/((u1mag)**2))*u1
u2

matrix([[0.33333333],
        [0.66666667],
        [0.33333333]])

In [14]:
V3 = V[:,2]
V3

matrix([[1],
        [1],
        [2]])

In [15]:
v3u1dot = np.linalg.norm(np.transpose(u1)@V3)
v3u1dot

2.0

In [17]:
u2mag = np.linalg.norm(u2)
u2mag

0.816496580927726

In [26]:
v3u2dot = np.linalg.norm(np.transpose(u2)@V3)
v3u2dot

1.6666666666666665

In [20]:
u3 = V3 - (v3u1dot/((u1mag)**2))*u1 - (v3u2dot/((u2mag)**2))*u2
u3

matrix([[-5.00000000e-01],
        [-2.22044605e-16],
        [ 5.00000000e-01]])

In [21]:
u1u3dot = np.linalg.norm(np.transpose(u1)@u3)
u1u3dot

4.440892098500626e-16

In [27]:
#normalize individual u1,u2,u3
#check the organility between u1,u2,u3
#finally make it orthonormal
print(u1)
print(u2)
print(u3)

[[ 1]
 [-1]
 [ 1]]
[[0.33333333]
 [0.66666667]
 [0.33333333]]
[[-5.00000000e-01]
 [-2.22044605e-16]
 [ 5.00000000e-01]]


In [28]:
u1u2dot = np.linalg.norm(np.transpose(u1)@u2)
u1u2dot

2.220446049250313e-16

In [29]:
u1u3dot = np.linalg.norm(np.transpose(u1)@u3)
u1u3dot

4.440892098500626e-16

In [30]:
u2u3dot = np.linalg.norm(np.transpose(u2)@u3)
u2u3dot

9.251858538542973e-17

In [31]:
u1mag

1.7320508075688772

In [32]:
u2mag

0.816496580927726

In [33]:
u3mag = np.linalg.norm(u3)
u3mag

0.7071067811865476

In [34]:
u1_cap = (1/u1mag)*u1
u1_cap

matrix([[ 0.57735027],
        [-0.57735027],
        [ 0.57735027]])

In [35]:
u2_cap = (1/u1mag)*u2
u2_cap

matrix([[0.19245009],
        [0.38490018],
        [0.19245009]])

In [36]:
u3_cap = (1/u1mag)*u3
u3_cap

matrix([[-2.88675135e-01],
        [-1.28197512e-16],
        [ 2.88675135e-01]])

In [ ]:
#assingment
